'use client';

import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import { Supplier, SupplierStatus, supplierStatusLabels, supplierStatusOptions } from '@/data/suppliers';

type SupplierFormValues = Omit<Supplier, 'id' | 'code' | 'supplyCount' | 'totalSupplyValue' | 'amountDue' | 'supplies' | 'timeline' | 'dateAdded'>;
type Props = { open: boolean; supplier?: Supplier | null; onClose: () => void; onSubmit: (values: SupplierFormValues) => void };
const defaultValues: SupplierFormValues = { name: '', contactName: '', phone: '', email: '', address: '', products: '', status: 'active', notes: '' };

export function SupplierFormModal({ open, supplier, onClose, onSubmit }: Props) {
  const [form, setForm] = useState(defaultValues);
  useEffect(() => { setForm(supplier ? { name: supplier.name, contactName: supplier.contactName, phone: supplier.phone, email: supplier.email, address: supplier.address, products: supplier.products, status: supplier.status, notes: supplier.notes } : defaultValues); }, [supplier, open]);
  if (!open) return null;
  const update = (field: keyof SupplierFormValues, value: string) => setForm((prev) => ({ ...prev, [field]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-[26px] border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><div><p className="text-sm font-medium text-blue-600">إدارة الموردين</p><h3 className="text-2xl font-bold text-slate-900">{supplier ? 'تعديل المورد' : 'مورد جديد'}</h3></div><button type="button" onClick={onClose} aria-label="إغلاق" className="rounded-xl border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><X className="h-5 w-5" /></button></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(form); }} className="space-y-5 p-6"><div className="grid gap-4 md:grid-cols-2">{([['name', 'اسم المورد أو الشركة'], ['contactName', 'اسم الشخص المسؤول'], ['phone', 'رقم الهاتف'], ['email', 'البريد الإلكتروني'], ['address', 'العنوان'], ['products', 'المنتجات أو المواد'] ] as [keyof SupplierFormValues, string][]).map(([field, label]) => <label key={field} className="block text-sm font-medium text-slate-700">{label}<input type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(event) => update(field, event.target.value)} required className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100" /></label>)}</div><label className="block text-sm font-medium text-slate-700">حالة المورد<select value={form.status} onChange={(event) => update('status', event.target.value as SupplierStatus)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-500"><option value="active">{supplierStatusLabels.active}</option>{supplierStatusOptions.filter((status) => status !== 'active').map((status) => <option key={status} value={status}>{supplierStatusLabels[status]}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">ملاحظات<textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} className="mt-2 min-h-[90px] w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 font-normal outline-none focus:border-blue-500" /></label><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-medium text-slate-700">إلغاء</button><button type="submit" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{supplier ? 'حفظ التغييرات' : 'إضافة المورد'}</button></div></form></div></div>;
}
